---
name: Publish Release Image
'on':
  release:
    branches:
    - main
    - master
    types:
    - published
jobs:
  build_and_publish:
    uses: ./workflows-templates/prod_publish_release_image.yml
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  