---
name: Run Trivy Scans
on:
    workflow_call:
jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Check out GitHub Repo
              uses: actions/checkout@v4

            - name: Build an image from Dockerfile
              run: |
                  git config --global --add safe.directory $GITHUB_WORKSPACE;
                  docker build -t trivy-test .

            - name: Rerun Trivy vulnerability scanner for GitHub security
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: "trivy-test"
                  format: "sarif"
                  output: "trivy-results.sarif"
                  timeout: "20m"
                  ignore-unfixed: true 
                  severity: 'CRITICAL,HIGH'

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: "trivy-results.sarif"
                  category: 'trivy-docker-scan'
