---
name: Run Trivy Scans

on:
  workflow_call:

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t local-scan:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "local-scan:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          timeout: "20m"
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        # Always run this step to upload results, even if the scan step failed
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: 'trivy-docker-scan'
